// BoardFusion server-authoritative room client with seat-token resume.
window.NET=(function(){
 let ws=null,url=null,room=null,seat=null,name=null,muted=false,closing=false,retries=0,queueing=false,connecting=null;
 const clientId=(()=>{let x=localStorage.getItem('bf_match_client');if(!x){x=(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random());localStorage.setItem('bf_match_client',x)}return x})();const handlers={};
 const on=(ev,fn)=>{handlers[ev]=fn},emit=(ev,d)=>{if(handlers[ev])handlers[ev](d)};
 const key=c=>'bf_room_v2_'+c;
 function send(m){if(ws&&ws.readyState===1)ws.send(JSON.stringify(m));else emit('error',{reason:'Not connected'});}
 function open(target){url=target;closing=false;if(ws&&ws.readyState===1)return Promise.resolve();if(connecting)return connecting;connecting=new Promise((resolve,reject)=>{const current=new WebSocket(url);ws=current;current.onopen=()=>{retries=0;connecting=null;resolve();};current.onerror=e=>{connecting=null;reject(e)};current.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch(_){return;}if(m.t==='v2-welcome'||m.t==='v2-match-found'){room=m.code;seat=m.seat;queueing=false;localStorage.setItem(key(room),JSON.stringify({code:room,token:m.token,name,url}));}if(m.t==='v2-match-queued')queueing=true;if(m.t==='v2-match-cancelled'||m.t==='v2-match-timeout')queueing=false;if(m.t==='v2-resumed'){room=m.code;seat=m.seat;emit('resumed',m);}if(m.t==='v2-displaced'){closing=true;emit('error',{reason:'This seat was resumed in another tab or device. Reload there to keep playing.'});return;}if(m.t==='v2-muted')muted=!!m.value;emit(m.t,m);};current.onclose=e=>{if(ws!==current)return;connecting=null;const wasQueueing=queueing;queueing=false;if(e&&e.code===4001){closing=true;emit('error',{reason:'This seat was resumed in another tab or device. Reload there to keep playing.'});return;}emit('closed',{wasQueueing});if(!closing&&room)setTimeout(reconnect,Math.min(8000,500*Math.pow(2,retries++)));};});}
 async function reconnect(){const saved=JSON.parse(localStorage.getItem(key(room))||'null');if(!saved)return;try{await open(saved.url||url);send({t:'v2-resume',code:saved.code,token:saved.token});}catch(_){if(!closing)setTimeout(reconnect,Math.min(8000,500*Math.pow(2,retries++)));}}
 const access=()=>window.BFCloud&&BFCloud.token||null;
 const create=n=>{name=n;send({t:'v2-create',name:n,accessToken:access()});};
 const join=(c,n)=>{name=n;send({t:'v2-join',code:c.toUpperCase(),name:n,accessToken:access()});};
 const match=n=>{name=n;send({t:'v2-match',name:n,clientId,accessToken:access()});};
 return{connect:open,create,join,match,cancelMatch:()=>send({t:'v2-match-cancel'}),on,start:()=>send({t:'v2-start'}),roll:()=>send({t:'v2-action',kind:'roll'}),pick:idx=>send({t:'v2-action',kind:'pick',idx}),react:emoji=>send({t:'v2-reaction',emoji}),mute:v=>{muted=!!v;send({t:'v2-mute',value:muted})},rematch:()=>send({t:'v2-rematch'}),get mode(){return room?'v2':'off'},get room(){return room},get seat(){return seat},get name(){return name},get muted(){return muted},get queueing(){return queueing}};
})();
